package com.liuyq.boot.zuul.model;

import java.io.Serializable;
import java.util.Date;

public class ApiConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FID
     *
     * @mbg.generated
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FUrl
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FRequestMethod
     *
     * @mbg.generated
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FVersion
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FCode
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FBusinessCode
     *
     * @mbg.generated
     */
    private String businessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FSystemCode
     *
     * @mbg.generated
     */
    private String systemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FGatewayUrl
     *
     * @mbg.generated
     */
    private String gatewayUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FDescription
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FRequestParamsSample
     *
     * @mbg.generated
     */
    private String requestParamsSample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FResponseSample
     *
     * @mbg.generated
     */
    private String responseSample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FIsEnabled
     *
     * @mbg.generated
     */
    private Boolean isEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FCreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apiconfig.FModifyTime
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FID
     *
     * @return the value of t_apiconfig.FID
     *
     * @mbg.generated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FID
     *
     * @param ID the value for t_apiconfig.FID
     *
     * @mbg.generated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FUrl
     *
     * @return the value of t_apiconfig.FUrl
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FUrl
     *
     * @param url the value for t_apiconfig.FUrl
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FRequestMethod
     *
     * @return the value of t_apiconfig.FRequestMethod
     *
     * @mbg.generated
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FRequestMethod
     *
     * @param requestMethod the value for t_apiconfig.FRequestMethod
     *
     * @mbg.generated
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FVersion
     *
     * @return the value of t_apiconfig.FVersion
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FVersion
     *
     * @param version the value for t_apiconfig.FVersion
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FCode
     *
     * @return the value of t_apiconfig.FCode
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FCode
     *
     * @param code the value for t_apiconfig.FCode
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FBusinessCode
     *
     * @return the value of t_apiconfig.FBusinessCode
     *
     * @mbg.generated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FBusinessCode
     *
     * @param businessCode the value for t_apiconfig.FBusinessCode
     *
     * @mbg.generated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FSystemCode
     *
     * @return the value of t_apiconfig.FSystemCode
     *
     * @mbg.generated
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FSystemCode
     *
     * @param systemCode the value for t_apiconfig.FSystemCode
     *
     * @mbg.generated
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode == null ? null : systemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FGatewayUrl
     *
     * @return the value of t_apiconfig.FGatewayUrl
     *
     * @mbg.generated
     */
    public String getGatewayUrl() {
        return gatewayUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FGatewayUrl
     *
     * @param gatewayUrl the value for t_apiconfig.FGatewayUrl
     *
     * @mbg.generated
     */
    public void setGatewayUrl(String gatewayUrl) {
        this.gatewayUrl = gatewayUrl == null ? null : gatewayUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FDescription
     *
     * @return the value of t_apiconfig.FDescription
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FDescription
     *
     * @param description the value for t_apiconfig.FDescription
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FRequestParamsSample
     *
     * @return the value of t_apiconfig.FRequestParamsSample
     *
     * @mbg.generated
     */
    public String getRequestParamsSample() {
        return requestParamsSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FRequestParamsSample
     *
     * @param requestParamsSample the value for t_apiconfig.FRequestParamsSample
     *
     * @mbg.generated
     */
    public void setRequestParamsSample(String requestParamsSample) {
        this.requestParamsSample = requestParamsSample == null ? null : requestParamsSample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FResponseSample
     *
     * @return the value of t_apiconfig.FResponseSample
     *
     * @mbg.generated
     */
    public String getResponseSample() {
        return responseSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FResponseSample
     *
     * @param responseSample the value for t_apiconfig.FResponseSample
     *
     * @mbg.generated
     */
    public void setResponseSample(String responseSample) {
        this.responseSample = responseSample == null ? null : responseSample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FIsEnabled
     *
     * @return the value of t_apiconfig.FIsEnabled
     *
     * @mbg.generated
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FIsEnabled
     *
     * @param isEnabled the value for t_apiconfig.FIsEnabled
     *
     * @mbg.generated
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FCreateTime
     *
     * @return the value of t_apiconfig.FCreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FCreateTime
     *
     * @param createTime the value for t_apiconfig.FCreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apiconfig.FModifyTime
     *
     * @return the value of t_apiconfig.FModifyTime
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apiconfig.FModifyTime
     *
     * @param modifyTime the value for t_apiconfig.FModifyTime
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApiConfig other = (ApiConfig) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getRequestMethod() == null ? other.getRequestMethod() == null : this.getRequestMethod().equals(other.getRequestMethod()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getBusinessCode() == null ? other.getBusinessCode() == null : this.getBusinessCode().equals(other.getBusinessCode()))
            && (this.getSystemCode() == null ? other.getSystemCode() == null : this.getSystemCode().equals(other.getSystemCode()))
            && (this.getGatewayUrl() == null ? other.getGatewayUrl() == null : this.getGatewayUrl().equals(other.getGatewayUrl()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getRequestParamsSample() == null ? other.getRequestParamsSample() == null : this.getRequestParamsSample().equals(other.getRequestParamsSample()))
            && (this.getResponseSample() == null ? other.getResponseSample() == null : this.getResponseSample().equals(other.getResponseSample()))
            && (this.getIsEnabled() == null ? other.getIsEnabled() == null : this.getIsEnabled().equals(other.getIsEnabled()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getRequestMethod() == null) ? 0 : getRequestMethod().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getBusinessCode() == null) ? 0 : getBusinessCode().hashCode());
        result = prime * result + ((getSystemCode() == null) ? 0 : getSystemCode().hashCode());
        result = prime * result + ((getGatewayUrl() == null) ? 0 : getGatewayUrl().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getRequestParamsSample() == null) ? 0 : getRequestParamsSample().hashCode());
        result = prime * result + ((getResponseSample() == null) ? 0 : getResponseSample().hashCode());
        result = prime * result + ((getIsEnabled() == null) ? 0 : getIsEnabled().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        return result;
    }
}