package com.liuyq.boot.zuul.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApiConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public ApiConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("FID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("FID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Integer value) {
            addCriterion("FID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Integer value) {
            addCriterion("FID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Integer value) {
            addCriterion("FID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("FID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Integer value) {
            addCriterion("FID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Integer value) {
            addCriterion("FID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Integer> values) {
            addCriterion("FID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Integer> values) {
            addCriterion("FID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Integer value1, Integer value2) {
            addCriterion("FID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Integer value1, Integer value2) {
            addCriterion("FID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("FUrl is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("FUrl is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("FUrl =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("FUrl <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("FUrl >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("FUrl >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("FUrl <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("FUrl <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("FUrl like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("FUrl not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("FUrl in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("FUrl not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("FUrl between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("FUrl not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIsNull() {
            addCriterion("FRequestMethod is null");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIsNotNull() {
            addCriterion("FRequestMethod is not null");
            return (Criteria) this;
        }

        public Criteria andRequestMethodEqualTo(String value) {
            addCriterion("FRequestMethod =", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotEqualTo(String value) {
            addCriterion("FRequestMethod <>", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodGreaterThan(String value) {
            addCriterion("FRequestMethod >", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodGreaterThanOrEqualTo(String value) {
            addCriterion("FRequestMethod >=", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLessThan(String value) {
            addCriterion("FRequestMethod <", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLessThanOrEqualTo(String value) {
            addCriterion("FRequestMethod <=", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLike(String value) {
            addCriterion("FRequestMethod like", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotLike(String value) {
            addCriterion("FRequestMethod not like", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIn(List<String> values) {
            addCriterion("FRequestMethod in", values, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotIn(List<String> values) {
            addCriterion("FRequestMethod not in", values, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodBetween(String value1, String value2) {
            addCriterion("FRequestMethod between", value1, value2, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotBetween(String value1, String value2) {
            addCriterion("FRequestMethod not between", value1, value2, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("FVersion is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("FVersion is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("FVersion =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("FVersion <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("FVersion >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("FVersion >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("FVersion <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("FVersion <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("FVersion like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("FVersion not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("FVersion in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("FVersion not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("FVersion between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("FVersion not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("FCode is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("FCode is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("FCode =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("FCode <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("FCode >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FCode >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("FCode <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("FCode <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("FCode like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("FCode not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("FCode in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("FCode not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("FCode between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("FCode not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIsNull() {
            addCriterion("FBusinessCode is null");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIsNotNull() {
            addCriterion("FBusinessCode is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeEqualTo(String value) {
            addCriterion("FBusinessCode =", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotEqualTo(String value) {
            addCriterion("FBusinessCode <>", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeGreaterThan(String value) {
            addCriterion("FBusinessCode >", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FBusinessCode >=", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLessThan(String value) {
            addCriterion("FBusinessCode <", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLessThanOrEqualTo(String value) {
            addCriterion("FBusinessCode <=", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLike(String value) {
            addCriterion("FBusinessCode like", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotLike(String value) {
            addCriterion("FBusinessCode not like", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIn(List<String> values) {
            addCriterion("FBusinessCode in", values, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotIn(List<String> values) {
            addCriterion("FBusinessCode not in", values, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeBetween(String value1, String value2) {
            addCriterion("FBusinessCode between", value1, value2, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotBetween(String value1, String value2) {
            addCriterion("FBusinessCode not between", value1, value2, "businessCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNull() {
            addCriterion("FSystemCode is null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNotNull() {
            addCriterion("FSystemCode is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeEqualTo(String value) {
            addCriterion("FSystemCode =", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotEqualTo(String value) {
            addCriterion("FSystemCode <>", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThan(String value) {
            addCriterion("FSystemCode >", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FSystemCode >=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThan(String value) {
            addCriterion("FSystemCode <", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThanOrEqualTo(String value) {
            addCriterion("FSystemCode <=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLike(String value) {
            addCriterion("FSystemCode like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotLike(String value) {
            addCriterion("FSystemCode not like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIn(List<String> values) {
            addCriterion("FSystemCode in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotIn(List<String> values) {
            addCriterion("FSystemCode not in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeBetween(String value1, String value2) {
            addCriterion("FSystemCode between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotBetween(String value1, String value2) {
            addCriterion("FSystemCode not between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlIsNull() {
            addCriterion("FGatewayUrl is null");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlIsNotNull() {
            addCriterion("FGatewayUrl is not null");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlEqualTo(String value) {
            addCriterion("FGatewayUrl =", value, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlNotEqualTo(String value) {
            addCriterion("FGatewayUrl <>", value, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlGreaterThan(String value) {
            addCriterion("FGatewayUrl >", value, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlGreaterThanOrEqualTo(String value) {
            addCriterion("FGatewayUrl >=", value, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlLessThan(String value) {
            addCriterion("FGatewayUrl <", value, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlLessThanOrEqualTo(String value) {
            addCriterion("FGatewayUrl <=", value, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlLike(String value) {
            addCriterion("FGatewayUrl like", value, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlNotLike(String value) {
            addCriterion("FGatewayUrl not like", value, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlIn(List<String> values) {
            addCriterion("FGatewayUrl in", values, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlNotIn(List<String> values) {
            addCriterion("FGatewayUrl not in", values, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlBetween(String value1, String value2) {
            addCriterion("FGatewayUrl between", value1, value2, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlNotBetween(String value1, String value2) {
            addCriterion("FGatewayUrl not between", value1, value2, "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("FDescription is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("FDescription is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("FDescription =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("FDescription <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("FDescription >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("FDescription >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("FDescription <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("FDescription <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("FDescription like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("FDescription not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("FDescription in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("FDescription not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("FDescription between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("FDescription not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleIsNull() {
            addCriterion("FRequestParamsSample is null");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleIsNotNull() {
            addCriterion("FRequestParamsSample is not null");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleEqualTo(String value) {
            addCriterion("FRequestParamsSample =", value, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleNotEqualTo(String value) {
            addCriterion("FRequestParamsSample <>", value, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleGreaterThan(String value) {
            addCriterion("FRequestParamsSample >", value, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleGreaterThanOrEqualTo(String value) {
            addCriterion("FRequestParamsSample >=", value, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleLessThan(String value) {
            addCriterion("FRequestParamsSample <", value, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleLessThanOrEqualTo(String value) {
            addCriterion("FRequestParamsSample <=", value, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleLike(String value) {
            addCriterion("FRequestParamsSample like", value, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleNotLike(String value) {
            addCriterion("FRequestParamsSample not like", value, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleIn(List<String> values) {
            addCriterion("FRequestParamsSample in", values, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleNotIn(List<String> values) {
            addCriterion("FRequestParamsSample not in", values, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleBetween(String value1, String value2) {
            addCriterion("FRequestParamsSample between", value1, value2, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleNotBetween(String value1, String value2) {
            addCriterion("FRequestParamsSample not between", value1, value2, "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleIsNull() {
            addCriterion("FResponseSample is null");
            return (Criteria) this;
        }

        public Criteria andResponseSampleIsNotNull() {
            addCriterion("FResponseSample is not null");
            return (Criteria) this;
        }

        public Criteria andResponseSampleEqualTo(String value) {
            addCriterion("FResponseSample =", value, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleNotEqualTo(String value) {
            addCriterion("FResponseSample <>", value, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleGreaterThan(String value) {
            addCriterion("FResponseSample >", value, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleGreaterThanOrEqualTo(String value) {
            addCriterion("FResponseSample >=", value, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleLessThan(String value) {
            addCriterion("FResponseSample <", value, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleLessThanOrEqualTo(String value) {
            addCriterion("FResponseSample <=", value, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleLike(String value) {
            addCriterion("FResponseSample like", value, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleNotLike(String value) {
            addCriterion("FResponseSample not like", value, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleIn(List<String> values) {
            addCriterion("FResponseSample in", values, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleNotIn(List<String> values) {
            addCriterion("FResponseSample not in", values, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleBetween(String value1, String value2) {
            addCriterion("FResponseSample between", value1, value2, "responseSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleNotBetween(String value1, String value2) {
            addCriterion("FResponseSample not between", value1, value2, "responseSample");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNull() {
            addCriterion("FIsEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNotNull() {
            addCriterion("FIsEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledEqualTo(Boolean value) {
            addCriterion("FIsEnabled =", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotEqualTo(Boolean value) {
            addCriterion("FIsEnabled <>", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThan(Boolean value) {
            addCriterion("FIsEnabled >", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FIsEnabled >=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThan(Boolean value) {
            addCriterion("FIsEnabled <", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("FIsEnabled <=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIn(List<Boolean> values) {
            addCriterion("FIsEnabled in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotIn(List<Boolean> values) {
            addCriterion("FIsEnabled not in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsEnabled between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsEnabled not between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("FCreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("FCreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("FCreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FCreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("FCreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("FCreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("FCreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("FCreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("FCreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("FCreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("FModifyTime is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("FModifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("FModifyTime =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("FModifyTime <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("FModifyTime >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FModifyTime >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("FModifyTime <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("FModifyTime <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("FModifyTime in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("FModifyTime not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("FModifyTime between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("FModifyTime not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andUrlLikeInsensitive(String value) {
            addCriterion("upper(FUrl) like", value.toUpperCase(), "url");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLikeInsensitive(String value) {
            addCriterion("upper(FRequestMethod) like", value.toUpperCase(), "requestMethod");
            return (Criteria) this;
        }

        public Criteria andVersionLikeInsensitive(String value) {
            addCriterion("upper(FVersion) like", value.toUpperCase(), "version");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("upper(FCode) like", value.toUpperCase(), "code");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLikeInsensitive(String value) {
            addCriterion("upper(FBusinessCode) like", value.toUpperCase(), "businessCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLikeInsensitive(String value) {
            addCriterion("upper(FSystemCode) like", value.toUpperCase(), "systemCode");
            return (Criteria) this;
        }

        public Criteria andGatewayUrlLikeInsensitive(String value) {
            addCriterion("upper(FGatewayUrl) like", value.toUpperCase(), "gatewayUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("upper(FDescription) like", value.toUpperCase(), "description");
            return (Criteria) this;
        }

        public Criteria andRequestParamsSampleLikeInsensitive(String value) {
            addCriterion("upper(FRequestParamsSample) like", value.toUpperCase(), "requestParamsSample");
            return (Criteria) this;
        }

        public Criteria andResponseSampleLikeInsensitive(String value) {
            addCriterion("upper(FResponseSample) like", value.toUpperCase(), "responseSample");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apiconfig
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}