package com.liuyq.boot.zuul.mapper;

import com.liuyq.boot.zuul.model.ApiConfig;
import com.liuyq.boot.zuul.model.ApiConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    long countByExample(ApiConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    int deleteByExample(ApiConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    int insert(ApiConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    int insertSelective(ApiConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    List<ApiConfig> selectByExample(ApiConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    ApiConfig selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiConfig record, @Param("example") ApiConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiConfig record, @Param("example") ApiConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apiconfig
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiConfig record);
}