package com.liuyq.boot.serviceA.bo;



import lombok.*;

import java.io.Serializable;
import java.util.Date;

/**
 * @author liuyq
 * @date 2019/6/11 0011 下午 19:59
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DemoBo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.kid
     *
     * @mbg.generated
     */
    private String kid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.group_id
     *
     * @mbg.generated
     */
    private String group_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.demo_field
     *
     * @mbg.generated
     */
    private String demo_field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.app_name
     *
     * @mbg.generated
     */
    private String app_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_demo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKid() {
        return kid;
    }

    public void setKid(String kid) {
        this.kid = kid;
    }

    public String getGroup_id() {
        return group_id;
    }

    public void setGroup_id(String group_id) {
        this.group_id = group_id;
    }

    public String getDemo_field() {
        return demo_field;
    }

    public void setDemo_field(String demo_field) {
        this.demo_field = demo_field;
    }

    public String getApp_name() {
        return app_name;
    }

    public void setApp_name(String app_name) {
        this.app_name = app_name;
    }

    public Date getCreate_time() {
        return create_time;
    }

    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}
