package com.liuyq.boot.serviceA.bo;

import lombok.*;

import java.io.Serializable;
import java.util.Date;

/**
 * @author liuyq
 * @date 2019/6/11 0011 下午 21:38
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TxExceptionBo implements Serializable {

    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tx_exception.group_id
     *
     * @mbg.generated
     */
    private String group_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tx_exception.unit_id
     *
     * @mbg.generated
     */
    private String unit_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tx_exception.mod_id
     *
     * @mbg.generated
     */
    private String mod_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tx_exception.transaction_state
     *
     * @mbg.generated
     */
    private Byte transaction_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tx_exception.registrar
     *
     * @mbg.generated
     */
    private Byte registrar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tx_exception.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tx_exception.ex_state
     *
     * @mbg.generated
     */
    private Byte ex_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tx_exception.create_time
     *
     * @mbg.generated
     */
    private Date create_time;
}
