package com.liuyq.boot.serviceB.model;

import java.io.Serializable;
import java.util.Date;

public class Demo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.kid
     *
     * @mbg.generated
     */
    private String kid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.group_id
     *
     * @mbg.generated
     */
    private String group_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.demo_field
     *
     * @mbg.generated
     */
    private String demo_field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.app_name
     *
     * @mbg.generated
     */
    private String app_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_demo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.id
     *
     * @return the value of t_demo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.id
     *
     * @param id the value for t_demo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.kid
     *
     * @return the value of t_demo.kid
     *
     * @mbg.generated
     */
    public String getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.kid
     *
     * @param kid the value for t_demo.kid
     *
     * @mbg.generated
     */
    public void setKid(String kid) {
        this.kid = kid == null ? null : kid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.group_id
     *
     * @return the value of t_demo.group_id
     *
     * @mbg.generated
     */
    public String getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.group_id
     *
     * @param group_id the value for t_demo.group_id
     *
     * @mbg.generated
     */
    public void setGroup_id(String group_id) {
        this.group_id = group_id == null ? null : group_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.demo_field
     *
     * @return the value of t_demo.demo_field
     *
     * @mbg.generated
     */
    public String getDemo_field() {
        return demo_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.demo_field
     *
     * @param demo_field the value for t_demo.demo_field
     *
     * @mbg.generated
     */
    public void setDemo_field(String demo_field) {
        this.demo_field = demo_field == null ? null : demo_field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.app_name
     *
     * @return the value of t_demo.app_name
     *
     * @mbg.generated
     */
    public String getApp_name() {
        return app_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.app_name
     *
     * @param app_name the value for t_demo.app_name
     *
     * @mbg.generated
     */
    public void setApp_name(String app_name) {
        this.app_name = app_name == null ? null : app_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.create_time
     *
     * @return the value of t_demo.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.create_time
     *
     * @param create_time the value for t_demo.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Demo other = (Demo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKid() == null ? other.getKid() == null : this.getKid().equals(other.getKid()))
            && (this.getGroup_id() == null ? other.getGroup_id() == null : this.getGroup_id().equals(other.getGroup_id()))
            && (this.getDemo_field() == null ? other.getDemo_field() == null : this.getDemo_field().equals(other.getDemo_field()))
            && (this.getApp_name() == null ? other.getApp_name() == null : this.getApp_name().equals(other.getApp_name()))
            && (this.getCreate_time() == null ? other.getCreate_time() == null : this.getCreate_time().equals(other.getCreate_time()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKid() == null) ? 0 : getKid().hashCode());
        result = prime * result + ((getGroup_id() == null) ? 0 : getGroup_id().hashCode());
        result = prime * result + ((getDemo_field() == null) ? 0 : getDemo_field().hashCode());
        result = prime * result + ((getApp_name() == null) ? 0 : getApp_name().hashCode());
        result = prime * result + ((getCreate_time() == null) ? 0 : getCreate_time().hashCode());
        return result;
    }
}