package com.liuyq.boot.serviceA.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TxExceptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public TxExceptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGroup_idIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroup_idIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroup_idEqualTo(String value) {
            addCriterion("group_id =", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idNotEqualTo(String value) {
            addCriterion("group_id <>", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idGreaterThan(String value) {
            addCriterion("group_id >", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idGreaterThanOrEqualTo(String value) {
            addCriterion("group_id >=", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idLessThan(String value) {
            addCriterion("group_id <", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idLessThanOrEqualTo(String value) {
            addCriterion("group_id <=", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idLike(String value) {
            addCriterion("group_id like", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idNotLike(String value) {
            addCriterion("group_id not like", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idIn(List<String> values) {
            addCriterion("group_id in", values, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idNotIn(List<String> values) {
            addCriterion("group_id not in", values, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idBetween(String value1, String value2) {
            addCriterion("group_id between", value1, value2, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idNotBetween(String value1, String value2) {
            addCriterion("group_id not between", value1, value2, "group_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idIsNull() {
            addCriterion("unit_id is null");
            return (Criteria) this;
        }

        public Criteria andUnit_idIsNotNull() {
            addCriterion("unit_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnit_idEqualTo(String value) {
            addCriterion("unit_id =", value, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idNotEqualTo(String value) {
            addCriterion("unit_id <>", value, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idGreaterThan(String value) {
            addCriterion("unit_id >", value, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idGreaterThanOrEqualTo(String value) {
            addCriterion("unit_id >=", value, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idLessThan(String value) {
            addCriterion("unit_id <", value, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idLessThanOrEqualTo(String value) {
            addCriterion("unit_id <=", value, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idLike(String value) {
            addCriterion("unit_id like", value, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idNotLike(String value) {
            addCriterion("unit_id not like", value, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idIn(List<String> values) {
            addCriterion("unit_id in", values, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idNotIn(List<String> values) {
            addCriterion("unit_id not in", values, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idBetween(String value1, String value2) {
            addCriterion("unit_id between", value1, value2, "unit_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idNotBetween(String value1, String value2) {
            addCriterion("unit_id not between", value1, value2, "unit_id");
            return (Criteria) this;
        }

        public Criteria andMod_idIsNull() {
            addCriterion("mod_id is null");
            return (Criteria) this;
        }

        public Criteria andMod_idIsNotNull() {
            addCriterion("mod_id is not null");
            return (Criteria) this;
        }

        public Criteria andMod_idEqualTo(String value) {
            addCriterion("mod_id =", value, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idNotEqualTo(String value) {
            addCriterion("mod_id <>", value, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idGreaterThan(String value) {
            addCriterion("mod_id >", value, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idGreaterThanOrEqualTo(String value) {
            addCriterion("mod_id >=", value, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idLessThan(String value) {
            addCriterion("mod_id <", value, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idLessThanOrEqualTo(String value) {
            addCriterion("mod_id <=", value, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idLike(String value) {
            addCriterion("mod_id like", value, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idNotLike(String value) {
            addCriterion("mod_id not like", value, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idIn(List<String> values) {
            addCriterion("mod_id in", values, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idNotIn(List<String> values) {
            addCriterion("mod_id not in", values, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idBetween(String value1, String value2) {
            addCriterion("mod_id between", value1, value2, "mod_id");
            return (Criteria) this;
        }

        public Criteria andMod_idNotBetween(String value1, String value2) {
            addCriterion("mod_id not between", value1, value2, "mod_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateIsNull() {
            addCriterion("transaction_state is null");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateIsNotNull() {
            addCriterion("transaction_state is not null");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateEqualTo(Byte value) {
            addCriterion("transaction_state =", value, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateNotEqualTo(Byte value) {
            addCriterion("transaction_state <>", value, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateGreaterThan(Byte value) {
            addCriterion("transaction_state >", value, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateGreaterThanOrEqualTo(Byte value) {
            addCriterion("transaction_state >=", value, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateLessThan(Byte value) {
            addCriterion("transaction_state <", value, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateLessThanOrEqualTo(Byte value) {
            addCriterion("transaction_state <=", value, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateIn(List<Byte> values) {
            addCriterion("transaction_state in", values, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateNotIn(List<Byte> values) {
            addCriterion("transaction_state not in", values, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateBetween(Byte value1, Byte value2) {
            addCriterion("transaction_state between", value1, value2, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andTransaction_stateNotBetween(Byte value1, Byte value2) {
            addCriterion("transaction_state not between", value1, value2, "transaction_state");
            return (Criteria) this;
        }

        public Criteria andRegistrarIsNull() {
            addCriterion("registrar is null");
            return (Criteria) this;
        }

        public Criteria andRegistrarIsNotNull() {
            addCriterion("registrar is not null");
            return (Criteria) this;
        }

        public Criteria andRegistrarEqualTo(Byte value) {
            addCriterion("registrar =", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarNotEqualTo(Byte value) {
            addCriterion("registrar <>", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarGreaterThan(Byte value) {
            addCriterion("registrar >", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarGreaterThanOrEqualTo(Byte value) {
            addCriterion("registrar >=", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarLessThan(Byte value) {
            addCriterion("registrar <", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarLessThanOrEqualTo(Byte value) {
            addCriterion("registrar <=", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarIn(List<Byte> values) {
            addCriterion("registrar in", values, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarNotIn(List<Byte> values) {
            addCriterion("registrar not in", values, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarBetween(Byte value1, Byte value2) {
            addCriterion("registrar between", value1, value2, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarNotBetween(Byte value1, Byte value2) {
            addCriterion("registrar not between", value1, value2, "registrar");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andEx_stateIsNull() {
            addCriterion("ex_state is null");
            return (Criteria) this;
        }

        public Criteria andEx_stateIsNotNull() {
            addCriterion("ex_state is not null");
            return (Criteria) this;
        }

        public Criteria andEx_stateEqualTo(Byte value) {
            addCriterion("ex_state =", value, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateNotEqualTo(Byte value) {
            addCriterion("ex_state <>", value, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateGreaterThan(Byte value) {
            addCriterion("ex_state >", value, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateGreaterThanOrEqualTo(Byte value) {
            addCriterion("ex_state >=", value, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateLessThan(Byte value) {
            addCriterion("ex_state <", value, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateLessThanOrEqualTo(Byte value) {
            addCriterion("ex_state <=", value, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateIn(List<Byte> values) {
            addCriterion("ex_state in", values, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateNotIn(List<Byte> values) {
            addCriterion("ex_state not in", values, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateBetween(Byte value1, Byte value2) {
            addCriterion("ex_state between", value1, value2, "ex_state");
            return (Criteria) this;
        }

        public Criteria andEx_stateNotBetween(Byte value1, Byte value2) {
            addCriterion("ex_state not between", value1, value2, "ex_state");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andGroup_idLikeInsensitive(String value) {
            addCriterion("upper(group_id) like", value.toUpperCase(), "group_id");
            return (Criteria) this;
        }

        public Criteria andUnit_idLikeInsensitive(String value) {
            addCriterion("upper(unit_id) like", value.toUpperCase(), "unit_id");
            return (Criteria) this;
        }

        public Criteria andMod_idLikeInsensitive(String value) {
            addCriterion("upper(mod_id) like", value.toUpperCase(), "mod_id");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_tx_exception
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_tx_exception
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}