# security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin

server:
  port: 8089

spring:
   application:
     name: boot-zuul-service

# /api-a/** 路由映射到 boot-serviceA 服务上   /api-b/**的路由映射到cloud-feign-serviceA 服务上  如果不写下面的配置，默认会将eurka上的所有服务都以serviceId作为 path
#zuul:
#  routes:
#    api-a:
#        path: /api-a/**
#        serviceId: serviceA
#    api-b:
#        path: /api-b/**
#        serviceId: serviceB
zuul:
  ribbon:
    ReadTimeout: 10000 #通讯超时时间
    ConnectTimeout: 10000 # 连接超时（ms）
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/