---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-cron-deployment
  namespace: f-paas
  labels:
    layer: f-paas
    env: all
    app: sentry-cron
    name: sentry-cron-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentry-cron
  template:
    metadata:
      labels:
        layer: f-paas
        env: all
        app: sentry-cron
        name: sentry-cron-server
    spec:
      containers:
        - name: sentry-cron
          image: sentry:latest
          imagePullPolicy: IfNotPresent
          args: ["run", "cron"]
          env:
            - name: SENTRY_SECRET_KEY
              value: "${SENTRY_SECRET_KEY}"
            - name: SENTRY_POSTGRES_HOST
              value: "postgres"
            - name: SENTRY_DB_PASSWORD
              value: "secret"
            - name: SENTRY_DB_USER
              value: "sentry"