---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentry-worker-deployment
  labels:
    layer: f-paas
    env: all
    app: sentry-worker
    name: sentry-worker-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        layer: f-paas
        env: all
        app: sentry-worker
        name: sentry-worker-server
    spec:
      containers:
        - name: sentry-worker
          image: sentry:latest
          imagePullPolicy: IfNotPresent
          command: ["run","worker"]
          env:
            - name: SENTRY_SECRET_KEY
              value: "${SENTRY_SECRET_KEY}"
            - name: SENTRY_POSTGRES_HOST
              value: "postgres"
            - name: SENTRY_DB_PASSWORD
              value: "secret"
            - name: SENTRY_DB_USER
              value: "sentry"