apiVersion: v1
kind: Service
metadata:
  name: sentry-proxy
  namespace: f-paas
spec:
  ports:
    - port: 30000
---
kind: Endpoints
apiVersion: v1
metadata:
  name: sentry-proxy
  namespace: f-paas
subsets:
  - addresses:
      - ip: 121.196.186.43
    ports:
      - port: 9000