#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin
server:
  port: 8082

spring:
  application:
    name: autoConfig-demo


hello:
   msg: jdbc:mysql://localhost:3306/testdate