# security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin

server:
  port: 8086

spring:
   application:
     name: cloud-feign-service-two
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/