# security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin

server:
  port: 8087

spring:
   application:
     name: boot-config-service
     # git管理
   cloud:
     config:
       enabled: true
       server:
        git:
          uri: https://github.com/liuyq913/liuyq-springBoot
          search-paths: liuyq-springBoot-config-service/config-repo/
          username: liuyq913
          password: 5078227ce
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/




