---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: eureka
          image: liuyuqing1212/liuyq-springboot-eureka:dev
          ports:
            - containerPort: 8092
      #使用regcred 认证文件来认证
      imagePullSecrets:
        - name: regcred
---

kind: Service
apiVersion: v1
metadata:
  name: liuyq-eureka-service
spec:
  selector:
    app: liuyq
  ports:
    - port: 8092 # Default port for image