# security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin

server:
  port: 8081

spring:
   application:
     name: boot-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/